var quotes = [
    "Manchester City",
    "Real Madrid",
    "Bayern Munchen",
    "Barcelona",
    "Inter Milan",
    "Liverpool FC",
    "Arsenal",
    "Barcelona",
    "Al Nassr",
    "Al Hilal",
    "Al Ittihad",
    "Al Ahli",
    "Navbahor",
    "Mumbai City",
    "Nasaf",
    "Atletico Madrid",
    "RB Leipzig",
    "Borussia Dortmund",
    "FC Porto",
    "Napoli",
    "AC Milan",
    "New Castle",
    "Benfica",
    "Real Sociedad",
    "Bayer Leverkusen",
    "Aston Villa",
    "Totenham",
    "PSG",
    "Feyenoord",
    "Juventus",
    "PSV",
    "Sporting",
    "Lazio",
    "Fiorentina",
    "Brighton",
    "Atalanta",
    "Manchester United",
    "Girona",
    "Sevillia",
    "West Ham UNT",
    "Lans",
    "Braga",
    "Brentford",
    "Roma",
    "Galatasaray",
    "Shakhtar",
    "Real Betis",
    "Atletic Bilbao",
    "Getafe",
    "Wolfsburg",
    "Wolverhampton",
  ];
  
  let quoteText = document.querySelector(".quote_text");
  
  function generateQuote() {
    var randomIndex = Math.floor(Math.random() * quotes.length);
    var quote = quotes[randomIndex]
    quoteText.innerHTML = '"' + quote + '"'
  }